# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-12 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
