# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-15 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='icon',
            field=models.CharField(default='<i class="fa fa-calendar-plus-o" aria-hidden="true"></i>', max_length=255),
        ),
    ]
