# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-12 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_job_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(max_length=255)),
                ('job', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobs.Job')),
            ],
        ),
    ]
