# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-12 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='notes',
            field=models.CharField(default='', max_length=255),
        ),
    ]
