# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-12 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20180111_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='notes',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
