# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-12 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20180111_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
