# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-12 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20180111_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
